# -----------------------------------------------------------------------------
# Copyright (c) 2025 Jyotirmay Gupta
#
# Project: Tiny Config Server
# Description: This is a personal project by Jyotirmay Gupta that implements a
# Spring Cloud Config Server. It serves centralized configuration for microservices
# by fetching configuration files from a remote Git repository.
#
# This code is intended for educational and personal use, demonstrating core backend
# concepts such as centralized configuration, environment-specific properties, and
# Spring Cloud integration.
#
# Licensed under the Apache License Version 2.0. See LICENSE file for more details.
# -----------------------------------------------------------------------------

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jyotirmay-gupta/tiny-config-repository.git
          clone-on-start: true
          username: jyotirmay-gupta
          password: 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
  security:
    user:
      name: tinyconfiguser
      password: password
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,configprops
  endpoint:
    health:
      show-details: always
