server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jyotirmay-gupta/tiny-config-repository.git
          clone-on-start: true
          username: jyotirmay-gupta
          password: ${CONFIG_PASSWORD}
  security:
    user:
      name: tinyconfiguser
      password: ${USER_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,configprops
  endpoint:
    health:
      show-details: always
